import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import Provider from "@/context/Provider";
import NavBar from "@/components/navbar/NavBar";
import "./globals.css";

const mulish = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Football Results",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${mulish.className} min-h-screen`}>
        <Provider>
          <header className="fixed z-20 w-full">
            <NavBar />
          </header>
          {children}
        </Provider>
      </body>
    </html>
  );
}
